[project]
name = 'Synthetic-Biology-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.gene-sequence]
path = 'contracts/gene-sequence.clar'
clarity_version = 2
epoch = 2.5

[contracts.organism-design]
path = 'contracts/organism-design.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
